world_name: one_rover_minimal

scenery:
  - uri: model://runway
    pose_degrees: "-29 545 0 0 0 363"

agents:
  - id: R0
    type: rover
    role: pursuer
    instance: 0
    spawn:
      xyz: [0.0, 0.0, 0.15]
      rpy_degrees: [0.0, 0.0, 0.0]
